### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by jmootrey** [osum4est/pancake#1]
Traceback (most recent call last):
  File "./pancake.py", line 4, in <module>
    import config
  File "/home/jeff/projects/git/pancake/config.py", line 4, in <module>
    from pandora.clientbuilder import FileBasedClientBuilder, SettingsDict
  File "/home/jeff/projects/git/pancake/pandora/**init**.py", line 13, in <module>
    from .transport import APITransport, Encryptor, DEFAULT_API_HOST
  File "/home/jeff/projects/git/pancake/pandora/transport.py", line 15, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by jmootrey** [comment]
Resolution - Install requests

pip install requests
